### PR TITLE
Add some *at functions and other miscellany

### PR DESCRIPTION
**Pull request by daewok**
Not quite ready for merge yet (I'm using this branch in another project of mine and want to make sure there's no other functions I want to add). But opening this now in case there's feedback or any major issues that would prevent this from getting merged.

This PR adds many `*at` variants of functions, to avoid certain race conditions. Additionally, it adds some `utime` variants.

The commit I'm most hesitant about is 475d8c2c2bd6af49e6bfbb9ee45bca9eef11147f (allowing access to the nanoseconds for the timestamps in `stat`). I'm pretty sure I made the change in a backwards compatible manner, but haven't tested on Windows or Darwin (yet) and don't have a BSD machine to test on.

### CODE REVIEW

**Comment by luismbo** [comment]
@daewok looks good. Perhaps @spwhitton would like to have a look as he's also interested in expanding the coverage of osicat-posix.

**Comment by daewok** [comment]
OK, I think this is ready now.

Sorry if it went off the rails with 95e2780, but I literally could not get osicat to load with SBCL on Windows without that commit. The problem is that osicat.lisp contains calls to some functions that are undefined on Windows. Those undefined functions have compiler macros associated with them that emit a full WARNING at compile time, which causes COMPILE-FILE to say the compilation failed and ASDF picks up on that.

**Comment by luismbo** [comment]
Thanks!

**Comment by spwhitton** [comment]
@luismbo thanks for the notification of this at the time, and sorry I wasn't available to review.  Great to see additions like this.

**Pull request merged**
