### PR TITLE
Add support for posix_fallocate

### PR DESCRIPTION
**Pull request by lispnik**
Hi, I needed to add support for my favourite posix function: posix_fallocate. It is a bit different to other posix calls in that it does NOT set errno. Instead, it communicates an error via return value. I think there is one other call like this: posix_fadvise (not implemented in this PR).

### CODE REVIEW

**Comment by luismbo** [comment]
That's a nice avatar. :) Is it a double bass?

Cherry-picked your commit into master: 17b4a8b. Thanks!

**Comment by luismbo** [comment]
@lispnik For some reason, your test fails on 32-bit CLISP. Any idea why?

```
Test POSIX-FALLOCATE.ERROR.1 failed
Form: 
(HANDLER-CASE
 (LET
  ((FILENAME
    (MAKE-PATHNAME :NAME "fallocate.error" :TYPE "1" :DEFAULTS
     *TEST-DIRECTORY*)))
  (HANDLER-CASE
   (LET*
    ((FD
      (OSICAT-POSIX:OPEN FILENAME OSICAT-POSIX:O-CREAT OSICAT-POSIX:O-RDWR)))
    (UNWIND-PROTECT (OSICAT-POSIX:POSIX-FALLOCATE FD 0 -100)
     (IGNORE-ERRORS (OSICAT-POSIX:CLOSE FD) (OSICAT-POSIX:UNLINK FILENAME))))
   (OSICAT-POSIX:EINVAL (C) 'FAILED)))
 (OSICAT-SYS:UNSUPPORTED-FUNCTION NIL (VALUES 'FAILED)))
Expected value: FAILED
Actual value: #<OSICAT-POSIX:EBADF "[No syscall name]" 9 :EBADF "Bad file descriptor">.
```

**Comment by lispnik** [comment]
Thanks, it's a cello. Do you play also?

I will check to see what is going on in clisp32

**Comment by lispnik** [comment]
@luismbo I believe I've fixed the test failure on 32-bit CLISP in b66b2a4

**Comment by luismbo** [comment]
Cherry-picked, thanks!

**Comment by luismbo** [comment]
@lispnik Oh, BTW, yeah, I play the double bass.

**Pull request closed without merging**
