### PR TITLE
Added the poll() system call and fixed ioctl only accepting a pointer argument

### PR DESCRIPTION
**Pull request by malcolmstill**
I'm in need of the ability to use poll() from a number of Lisp implementations and couldn't find it in osicat; this pull requests adds the system call.

### CODE REVIEW

**Comment by Ferada** [comment]
The return value needs to be checked and an error raised IMO. The example in the docstring needs to have the `-1` as the first argument. Also the use of `values-list` at least is questionable.

Ideally this would have a split low and high level interface such that the use of this interface can be less costly.

**Comment by malcolmstill** [comment]
Thanks for the feedback.

> The return value needs to be checked and an error raised IMO.
 
> Ideally this would have a split low and high level interface such that the use of this interface can be less costly.

Based on your feedback I would suggest something like the following as the low level interface with error checking. `poll` would now return `T` or `NIL` if there is or is not an event. As well as checking the return value it also examines the revents for errors on each file descriptor.

```
(defun poll (pollfds nfds timeout)
  (let ((r (%poll pollfds nfds timeout)))
    (when (= r -1)
      (posix-error))
    (when (> r 0)
        (loop :for i :from 0 :to (- nfds 1)
           :do (with-foreign-slots ((fd revents) (mem-aptr pollfds '(:struct pollfd) i) (:struct pollfd))
                 (cond
                   ((= revents (logand pollerr)) (error 'poll-error :fd fd))
                   ((= revents (logand pollhup)) (error 'poll-hangup :fd fd))
                   ((= revents (logand pollnval)) (error 'poll-invalid :fd fd))))
           :finally (return t)))))
```

I would then suggest a couple of higher level helpers for setting up the pollfd structs:

```
(defun poll-return-event (pollfd)
  (with-foreign-slots ((revents) pollfd (:struct pollfd))
    revents))

(defmacro with-pollfds ((name &rest specs) &body body)
  (let ((nfds (length specs)))
    `(with-foreign-object (,name '(:struct pollfd) ,nfds)
       (let (,@(loop :for i :from 0 :to (- nfds 1)
                  :collecting (let ((spec (nth i specs)))
                        `(,(first spec) (mem-aptr ,name '(:struct pollfd) ,i)))))
         ,@(loop :for i :from 0 :to (- nfds 1)
              :collecting (let ((spec (nth i specs)))
                    `(with-foreign-slots ((fd events revents) ,(first spec) (:struct pollfd))
                       (setf fd ,(second spec))
                       (setf events (logior ,@(rest (rest spec))))
                       (setf revents 0))))
         ,@body))))
```

This allows a nice interface without any costs associated with allocating the pollfd structs (every loop if it is contained within such) or using `values-list`.

An example then might look like:

```
(nix:with-pollfds (pollfds
		   (one fd-1 nix:pollin)
		   (two fd-2 nix:pollin))
  (loop :do
     (let ((event (nix:poll pollfds 2 -1)))
       (when event
         (when (= (nix:poll-return-event one) nix:pollin)
           (format t "Activity on first fd~%"))
         (when (= (nix:poll-return-event two) nix:pollin)
           (format t "Activity on second fd~%"))))))))
```

Thoughts?

**Comment by Ferada** [comment]
I'm not sure about the individual errors on each FD, is it useful for you to error out immediately in any of those cases?

Other than that the split looks good to me, I hadn't thought about assigning the individual structs to variables like that.

**Comment by malcolmstill** [comment]
In all honesty, I'm not sure either: I'd be happy enough to remove those checks and leave it up to the user.

**Comment by Ferada** [comment]
Btw. you have seen iolib and it's facilities for this right?

**Comment by malcolmstill** [comment]
I only became aware about iolib after submitting the pull request. Obviously there is potential for overlap. It still seems like poll should be available in osicat but I understand if there is resistance to a duplication of effort. Also not a huge fan of the requirement on libfixposix. 

I'm removing the revent check from the pull request.

**Comment by malcolmstill** [comment]
I noticed a small bug in ioctl: it should also accept an integer argument. I've added the fix to this pull request.

**Pull request closed without merging**
